# Generated by Django 3.1.3 on 2021-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20210114_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
