# Generated by Django 3.1.3 on 2021-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_auto_20210114_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_free',
            field=models.BooleanField(default=False),
        ),
    ]
