# Generated by Django 3.1.3 on 2021-01-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20210112_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='leanrner_id',
            new_name='learner_id',
        ),
    ]
