# Generated by Django 3.1.5 on 2021-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20210112_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learner',
            name='learner_phno',
            field=models.IntegerField(),
        ),
    ]
