# Generated by Django 3.1.3 on 2021-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_auto_20210114_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_free',
            field=models.BooleanField(default=True),
        ),
    ]
