# Generated by Django 3.1.3 on 2021-01-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_auto_20210115_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='options',
            new_name='option1',
        ),
        migrations.RemoveField(
            model_name='learner',
            name='courses_enrolled',
        ),
        migrations.AddField(
            model_name='quiz',
            name='option2',
            field=models.TextField(default='No option'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option3',
            field=models.TextField(default='No option'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='option4',
            field=models.TextField(default='No option'),
        ),
    ]
