# Generated by Django 3.1.3 on 2021-01-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_auto_20210116_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='score',
        ),
    ]
