# Generated by Django 3.1.3 on 2021-01-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_remove_learner_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
